name: kas golang application PR pipeline
on: push
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: fetch actions repo
      uses: actions/checkout@v2
      with:
        repository: "joosangkim/gx-gh-actions"
        path: "./actions"
    - name: prepare golang env
      uses: "./actions/kas/go/prepare"
      with:
        version: "1.16"      
