name: kas golang application PR pipeline
on: ["push"]
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/module/test
      with:
        repo: | 
            *.go
            **/*.go
            go.mod
            go.sum
            Makefile
            !.circleci
            !.github/workflows
            !fixtures/helm-chart
