name: kas golang application PR pipeline
on: ["push"]
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test1
      shell: bash
      id: test1
      run: |
          echo "** SET project **"
          echo ::set-output name=project::$(echo ${{ github.repository }} | sed -E 's|(^.*\/)||')
    - name: test2
      shell: bash
      run: |
        echo ${{ steps.test1.outputs.project }}
    - uses: ./.github/workflows/module/test
      with:
        repo: | 
            *.go
            **/*.go
            go.mod
            go.sum
            Makefile
            !.circleci
            !.github/workflows
            !fixtures/helm-chart
