name: kas golang application PR pipeline
on: push
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: fetch actions repo
      uses: actions/checkout@v2
      with:
        repository: "joosangkim/gx-gh-actions"
        path: "./.github/actions"
        token: "${secret.TEST_PAT}"
    - name: prepare golang env
      uses: "./.github/actions/kas/go/prepare"
      with:
        version: "1.16"
