name: kas golang application PR pipeline
on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        description: 'Unit test module for Reusing .'
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fetch actions repo
      uses: actions/checkout@v2
      with:
        repository: "joosangkim/gx-gh-actions"
        path: "./.github/actions"
    - name: prepare golang env
      uses: "./.github/actions/kas/go/prepare"
      with:
        version: "1.16"
