name: kas golang application PR pipeline
on: ["push"]
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      shell: bash
      run: |
        REF="${{ env.GITHUB_REF }}"
        echo $(echo ${{ github.repository }} | sed -E 's|(^.*\/)||')
        echo $(echo ${{ github.sha }} | cut -c-8)
        REF="${{ github.ref_name }}"
        echo $REF
