name: kas golang application PR pipeline
on: push
permissions:
      id-token: write
      contents: read  
jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: fetch actions repo
      uses: actions/checkout@v2
      with:
        repository: "joosangkim/gx-gh-actions"
        path: "./actions"
        ssh-key: "${{ secrets.PRIVATE_SSH_KEY }}"    
    - name: aws credentials
      uses: "./actions/common/credentials/aws"
    - name: Test aws cli
      shell: bash
      run: |
        aws eks update-kubeconfig --name service-dev
